const entries = [
  { type: "CONSTELLATION FOLKLORE", title: "Orion / many tellings", text: "Across cultures, the same bright stars have been connected into different stories. This entry is a comparison prompt, not a single ‘original’ myth.", source: "SOURCE LABEL: SKY & TELESCOPE — CONSTELLATION GUIDE (EDUCATIONAL SUMMARY)" },
  { type: "HISTORICAL PROBE", title: "Voyager Golden Record", text: "A curated message launched with the Voyager spacecraft. It contains sounds, images, and greetings chosen to represent life on Earth; its interpretation by another audience is unknown.", source: "SOURCE LABEL: NASA — VOYAGER GOLDEN RECORD (PUBLIC MISSION ARCHIVE)" },
  { type: "CONSTELLATION FOLKLORE", title: "The Southern Cross / navigation", text: "Crux has been used as a directional reference in southern skies. Treat this as a navigation history note; stories and names vary by community.", source: "SOURCE LABEL: INTERNATIONAL ASTRONOMICAL UNION — CONSTELLATION BOUNDARIES" },
  { type: "HISTORICAL PROBE", title: "Mars Pathfinder", text: "A fictional field note about a real mission: Pathfinder demonstrated a landing system and the Sojourner rover’s mobility. The specimen cards here are simplified for classroom use.", source: "SOURCE LABEL: NASA — MARS PATHFINDER MISSION OVERVIEW" }
];

const discoveryTimeline = [
  { date: "2ND MILLENNIUM BCE → ANTIQUITY", title: "The five naked-eye planets", people: "Babylonian astronomers and skywatchers worldwide", detail: "Mercury, Venus, Mars, Jupiter, and Saturn are visible without a telescope and have no single known discoverer. Babylonian astronomers were tracking and recording their motions by the 2nd millennium BCE, alongside skywatchers in many other civilizations." },
  { date: "3RD CENTURY BCE · PUBLISHED 1543", title: "Earth as a moving planet", people: "Aristarchus of Samos · Nicolaus Copernicus", detail: "Many influential ancient cosmologies placed a stationary Earth at the center. Aristarchus proposed that Earth orbits the Sun; the idea was not widely adopted. Copernicus later set out a mathematical heliocentric system in De revolutionibus (1543)." },
  { date: "EARLY 17TH CENTURY", title: "Telescopic planetary astronomy", people: "Galileo Galilei", detail: "Galileo helped pioneer modern telescopic study of the planets, observing Venus's phases and Jupiter's moons. These observations transformed astronomy; they were not discoveries of the five planets known since antiquity." },
  { date: "13 MAR 1781", title: "Uranus", people: "William Herschel", detail: "Herschel first reported Uranus as a comet. Continued observation established its planetary orbit, making it the first planet discovered in modern times rather than known since antiquity." },
  { date: "1 JAN 1801", title: "Ceres", people: "Giuseppe Piazzi", detail: "Piazzi discovered Ceres between Mars and Jupiter. First considered a planet, it was later classified as an asteroid and is now recognized as a dwarf planet." },
  { date: "23 SEP 1846", title: "Neptune", people: "Johann Galle, following Urbain Le Verrier's prediction", detail: "Le Verrier used irregularities in Uranus's orbit to calculate the position of an unseen planet. Galle, working with Heinrich d'Arrest, observed Neptune near the prediction. It became the first planet discovered with a major role for mathematical prediction from orbital irregularities." },
  { date: "18 FEB 1930", title: "Pluto", people: "Clyde Tombaugh", detail: "Tombaugh identified Pluto by comparing photographic plates from a systematic survey at Lowell Observatory in Arizona." },
  { date: "2005 → 2006", title: "Eris and the dwarf-planet category", people: "Discovery team led by Michael Brown · International Astronomical Union", detail: "The discovery of Eris, a distant body comparable in size to Pluto, intensified debate over the definition of a planet. In 2006 the IAU adopted a formal planet definition and established the dwarf-planet category; Eris was subsequently classified as a dwarf planet." },
];

export default function CulturalHistoryPage() {
  return <div className="page"><div className="section-heading"><span className="eyebrow">ARCHIVE / 004</span><h1>Cultural <em>History</em></h1><p>Explore how skywatching, new instruments, and mathematical predictions changed our understanding of the solar system.</p></div><section className="discovery-archive"><div className="archive-heading"><span className="eyebrow">PLANETARY DISCOVERY / TIMELINE</span><h2>From ancient skies to modern astronomy</h2><p>“Discovery” has different meanings for worlds visible to the naked eye and those found with telescopes or mathematical predictions.</p></div><div className="discovery-timeline">{discoveryTimeline.map((item, index) => <article className="discovery-entry" key={item.title}><div className="discovery-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="discovery-entry-card"><span className="eyebrow">{item.date}</span><h3>{item.title}</h3><strong>{item.people}</strong><p>{item.detail}</p></div></article>)}</div><p className="archive-note">Historical summary. Dates refer to documented discovery or publication events; ancient observations span multiple cultures and records.</p></section><div className="history-grid">{entries.map((entry, i) => <article className="history-card" key={entry.title}><span className="card-index">0{i + 1} / {entry.type}</span><h2>{entry.title}</h2><p>{entry.text}</p><small>{entry.source}</small></article>)}</div></div>;
}
